import {
  Landmark, Dices, Briefcase, Pickaxe, PawPrint,
  TrendingUp, ShoppingCart, Ticket, Wrench, Lock,
  Fish,
} from 'lucide-react'

export const CATEGORIES = [
  {
    id: 'economy',
    label: 'Economy',
    Icon: Landmark,
    color: '#5bc4e0',
    commands: [
      { name: '/balance [user]',         desc: 'Check wallet, bank, and net worth.',              details: 'Cooldown: None · Option: user (optional)' },
      { name: '/deposit <amount | all>',  desc: 'Deposit coins into bank safety.',                 details: 'Cooldown: None · Protects coins from robberies' },
      { name: '/withdraw <amount | all>', desc: 'Withdraw coins to wallet for spending.',          details: 'Cooldown: None' },
      { name: '/pay <user> <amount>',    desc: 'Send wallet coins to another user.',              details: 'Cooldown: None · Action is irreversible' },
      { name: '/daily',                  desc: 'Claim daily allowance of 500-1000 coins.',        details: 'Cooldown: 24 hours' },
      { name: '/weekly',                 desc: 'Claim weekly allowance of 5000-8000 coins.',      details: 'Cooldown: 7 days' },
      { name: '/monthly',                desc: 'Claim monthly allowance of 25000-40000 coins.',   details: 'Cooldown: 30 days' },
      { name: '/beg',                    desc: 'Beg for spare change.',                           details: 'Cooldown: 45s · Payout: 20-120 coins' },
      { name: '/search',                 desc: 'Search locations for loose change or items.',     details: 'Cooldown: 30s · Payout depends on risk level' },
    ],
  },
  {
    id: 'gambling',
    label: 'Gambling',
    Icon: Dices,
    color: '#f59e0b',
    commands: [
      { name: '/coinflip <amount> <heads | tails>', desc: 'Standard 50/50 flip.',                              details: 'Cooldown: 15s · Win: 2x bet' },
      { name: '/slots <amount>',                    desc: 'Spin reels and match symbols.',                     details: 'Cooldown: 15s · Win up to 50x bet' },
      { name: '/blackjack <amount>',                desc: 'Play Blackjack against the dealer.',                details: 'Cooldown: 15s · Win: 2x bet (2.5x blackjack)' },
      { name: '/roulette <amount> <bet>',           desc: 'Bet on colors or specific numbers.',                details: 'Cooldown: 15s · Win: Red/Black (2x), Green (14x), Number (36x)' },
      { name: '/higherlower <amount>',              desc: 'Guess if the next card is higher/lower.',           details: 'Cooldown: 15s · Multiplier climbs up to 30x' },
      { name: '/crash <amount>',                    desc: 'Cash out before the multiplier crashes.',           details: 'Cooldown: 15s · Volatility: Extreme' },
      { name: '/rps <amount>',                      desc: 'Classic Rock-Paper-Scissors.',                      details: 'Cooldown: 15s · Draw refunds bet' },
      { name: '/cockfight <amount>',                desc: 'Bet on your active pet rooster.',                   details: 'Cooldown: 15s (Rooster recovery: 5m)' },
      { name: '/horserace <amount> <horse>',        desc: 'Bet on 1 of 5 horses.',                            details: 'Cooldown: 15s · Win: 2x to 8x (depends on odds)' },
      { name: '/scratchcard [tier]',                desc: 'Match 3 items on a 3x3 grid.',                     details: 'Cooldown: 15s · Win up to 20x' },
      { name: '/mines <bet> [mines]',               desc: 'Reveal safe tiles to multiply your bet.',           details: 'Cooldown: 15s · Grid size: 4x4' },
      { name: '/rob <target>',                      desc: 'Attempt to steal from another wallet.',             details: 'Cooldown: 10m · Success: 40% (fine on failure)' },
      { name: '/lottery buy <tickets>',             desc: 'Buy lottery tickets (100 coins each).',             details: 'Cooldown: None · Draw occurs every 24 hours' },
      { name: '/lottery info',                      desc: 'Check current lottery pot, round, and your tickets.', details: 'Cooldown: None' },
    ],
  },
  {
    id: 'jobs',
    label: 'Jobs & Work',
    Icon: Briefcase,
    color: '#06b6d4',
    commands: [
      { name: '/job list',        desc: 'Browse all available jobs, ranks, and pay.',            details: 'Cooldown: None' },
      { name: '/job apply <job>', desc: 'Apply for a job path.',                                 details: 'Cooldown: None · Requires minimum level to apply' },
      { name: '/job info',        desc: 'Check current job performance and streak details.',     details: 'Cooldown: None' },
      { name: '/job resign',      desc: 'Resign from your current career.',                      details: 'Cooldown: None · Resets rank progress' },
      { name: '/job prestige',    desc: 'Reset job rank for permanent pay multipliers.',         details: 'Cooldown: None · Max prestige: 5' },
      { name: '/work',            desc: 'Work your active job shift.',                           details: 'Cooldown: 1h · Promotes every 15 shifts' },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    Icon: Pickaxe,
    color: '#10b981',
    commands: [
      { name: '/hunt', desc: 'Hunt for game in the wilderness.',      details: 'Cooldown: 1h · Requires Hunting Rifle' },
      { name: '/dig',  desc: 'Dig for buried treasures.',             details: 'Cooldown: 45m · Requires Shovel' },
      { name: '/chop', desc: 'Chop down trees for valuable timber.',  details: 'Cooldown: 45m · Requires Axe' },
      { name: '/mine', desc: 'Mine ore veins and rare gems.',         details: 'Cooldown: 45m · Requires Pickaxe' },
      { name: '/fish', desc: 'Cast a fishing line.',                  details: 'Cooldown: 45m · Requires Fishing Pole' },
    ],
  },
  {
    id: 'pets',
    label: 'Pets',
    Icon: PawPrint,
    color: '#ec4899',
    commands: [
      { name: '/pet adopt <type> <name>', desc: 'Adopt a pet companion.',                                    details: 'Cooldown: None · Costs coins · Max pets: 5' },
      { name: '/pet status',              desc: 'View active pet hunger, happiness, energy, and health.',    details: 'Cooldown: None' },
      { name: '/pet feed',                desc: 'Restore hunger and health.',                                details: 'Cooldown: 1h (cooldown-free with Pet Food item)' },
      { name: '/pet play',                desc: 'Boost happiness, uses energy.',                             details: 'Cooldown: 30m' },
      { name: '/pet list',                desc: 'View all owned pets and stats.',                            details: 'Cooldown: None · Set active companion via select menu' },
      { name: '/pet select <id>',         desc: 'Set active companion pet.',                                 details: 'Cooldown: None' },
      { name: '/pet rename <name>',       desc: 'Give your active pet a new name.',                         details: 'Cooldown: None' },
      { name: '/pet evolve',              desc: 'Evolve active pet at lvl 10 (Adult) and lvl 25 (Elder).',  details: 'Cooldown: None' },
      { name: '/pet release <id>',        desc: 'Release owned pet into wild.',                              details: 'Cooldown: None · Action is permanent' },
    ],
  },
  {
    id: 'stocks',
    label: 'Stocks & Trading',
    Icon: TrendingUp,
    color: '#a78bfa',
    exchanges: [
      'NYSE — 50 stocks (BRK, JPM, V, LLY, GS…)',
      'NASDAQ — 50 stocks (AAPL, NVDA, TSLA, META, COIN…)',
      'LSE — 50 stocks (AZN, SHEL, GAW, OCDO…)',
      'TSE — 50 stocks (NTD, TYT, SNY, KNM…)',
      'HKEX — 50 stocks (TCT, BABA, BYD, EVG…)',
      'NSE — 50 stocks (RELI, TCS, MARUTI, BAJFIN…)',
      'CRYPTO — 50 coins (BTC, ETH, SOL, PEPE, FLOKI…)',
    ],
    commands: [
      { name: '/stocks view <exchange>',        desc: 'View stock exchange listings.',              details: 'Cooldown: None · Prices update every 30 minutes' },
      { name: '/stocks info <ticker>',          desc: 'Detailed stock metrics & volatility.',       details: 'Cooldown: None · Shows personal holdings if owned' },
      { name: '/stocks buy <ticker> <shares>',  desc: 'Purchase stock shares.',                     details: 'Cooldown: None · Deducted from wallet balance' },
      { name: '/stocks sell <ticker> <shares | all>', desc: 'Sell stock shares.',                   details: 'Cooldown: None · Earned added to wallet balance' },
      { name: '/stocks portfolio [user]',       desc: 'View current stock portfolio.',              details: 'Cooldown: None · Displays average buy prices and P&L' },
    ],
  },
  {
    id: 'shop',
    label: 'Shop & Items',
    Icon: ShoppingCart,
    color: '#f97316',
    commands: [
      { name: '/shop view [category]',     desc: 'Browse the shop items.',              details: 'Cooldown: None · Category filtering dropdown available' },
      { name: '/shop buy <item>',          desc: 'Buy permanent tools or consumables.', details: 'Cooldown: None · Tools are one-time purchase' },
      { name: '/shop sell <item> [amount]',desc: 'Sell gathered loot or items.',        details: 'Cooldown: None · Added to wallet balance' },
      { name: '/inventory [user]',         desc: 'View owned items, tools, and value.', details: 'Cooldown: None · Displays estimated sell value' },
      { name: '/lootbox open <tier>',      desc: 'Open a lootbox from your inventory.', details: 'Cooldown: None · Rewards coins, XP, and consumable items' },
      { name: '/lootbox tiers',            desc: 'View all lootbox tiers, drop rates, and potential rewards.', details: 'Cooldown: None' },
    ],
  },
  {
    id: 'lottery',
    label: 'Lottery',
    Icon: Ticket,
    color: '#eab308',
    commands: [
      { name: '/lottery buy <tickets>', desc: 'Buy lottery tickets (100 coins each).', details: 'Cooldown: None · Draw every 24 hours' },
      { name: '/lottery info',          desc: 'Check pot, round, and your tickets.',   details: 'Cooldown: None' },
    ],
  },
  {
    id: 'utility',
    label: 'Utility',
    Icon: Wrench,
    color: '#38bdf8',
    commands: [
      { name: '/ping',               desc: 'Check bot latency.',                                        details: 'Cooldown: None' },
      { name: '/rank [user]',        desc: 'Check level, total XP, and progression.',                   details: 'Cooldown: None · View level pay bonuses' },
      { name: '/cooldowns [user]',   desc: 'Check active action and reward cooldowns.',                 details: 'Cooldown: None · Option: user (optional)' },
      { name: '/profile [user]',     desc: 'View a rich profile card with stats, job, and active pet.', details: 'Cooldown: None' },
      { name: '/leaderboard <type>', desc: 'View top players by XP, coins, or net worth.',             details: 'Cooldown: None · Types: xp, coins, networth' },
      { name: '/help',               desc: 'Browse all bot commands by category.',                      details: 'Cooldown: None · Dropdown & page pagination' },
    ],
  },
  {
    id: 'admin',
    label: 'Administrator',
    Icon: Lock,
    color: '#f43f5e',
    commands: [
      { name: '/admin balance-give <user> <amount>',      desc: 'Give coins to a user.',             details: 'Requires: Bot Developer' },
      { name: '/admin balance-remove <user> <amount>',    desc: 'Remove coins from a user.',         details: 'Requires: Bot Developer' },
      { name: '/admin balance-set <user> <amount>',       desc: "Set a user's balance directly.",    details: 'Requires: Bot Developer' },
      { name: '/admin item-give <user> <item> [qty]',     desc: 'Give an item to a user.',           details: 'Requires: Bot Developer · Autocomplete support' },
      { name: '/admin item-remove <user> <item> [qty]',   desc: 'Remove an item from a user.',       details: 'Requires: Bot Developer · Autocomplete support' },
      { name: '/admin xp-add <user> <amount>',            desc: 'Add XP to a user.',                 details: 'Requires: Bot Developer' },
      { name: '/admin cooldown-reset <user> <action>',    desc: 'Reset cooldowns for a user.',       details: 'Requires: Bot Developer' },
    ],
  },
]

export const ALL_COMMANDS = CATEGORIES.flatMap(cat =>
  cat.commands.map(cmd => ({ ...cmd, category: cat.id, catLabel: cat.label, catColor: cat.color }))
)
